"""profile update

Revision ID: 2d0967517e9d
Revises: e772d1d698fd
Create Date: 2026-01-01 22:53:22.551351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0967517e9d'
down_revision: Union[str, Sequence[str], None] = 'e772d1d698fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('college', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('passing_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'passing_year')
    op.drop_column('profiles', 'degree')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'college')
    op.drop_column('profiles', 'bio')
    # ### end Alembic commands ###
