"""viral

Revision ID: 42d849d2ecaf
Revises: b566eede9c9a
Create Date: 2026-01-12 00:51:20.411533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d849d2ecaf'
down_revision: Union[str, Sequence[str], None] = 'b566eede9c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.drop_column('document_chunks', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('document_chunks', 'chunk_index')
    # ### end Alembic commands ###
