"""ve

Revision ID: 4488c6875c2b
Revises: c1c90f1f02d7
Create Date: 2026-01-18 00:26:35.810561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4488c6875c2b'
down_revision: Union[str, Sequence[str], None] = 'c1c90f1f02d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('short_answers_session_id_key'), 'short_answers', type_='unique')
    op.drop_constraint(op.f('short_answers_session_id_fkey'), 'short_answers', type_='foreignkey')
    op.drop_column('short_answers', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_answers', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('short_answers_session_id_fkey'), 'short_answers', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('short_answers_session_id_key'), 'short_answers', ['session_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
