"""index

Revision ID: a8335ed8ca30
Revises: 8c2d66f2df87
Create Date: 2026-01-10 23:14:38.281333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8335ed8ca30'
down_revision: Union[str, Sequence[str], None] = '8c2d66f2df87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mcq_attempts_session_id_fkey'), 'mcq_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'mcq_attempts', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcq_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('mcq_attempts_session_id_fkey'), 'mcq_attempts', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
