"""head

Revision ID: b7ec3cd0f129
Revises: 2fe359a8e883
Create Date: 2026-01-05 21:30:50.533213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ec3cd0f129'
down_revision: Union[str, Sequence[str], None] = '2fe359a8e883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mcq_attempts', ['session_id'])
    op.create_unique_constraint(None, 'short_answer_attempts', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_answer_attempts', type_='unique')
    op.drop_constraint(None, 'mcq_attempts', type_='unique')
    # ### end Alembic commands ###
