"""ve

Revision ID: c1c90f1f02d7
Revises: 073f19a2e792
Create Date: 2026-01-18 00:21:17.427121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c90f1f02d7'
down_revision: Union[str, Sequence[str], None] = '073f19a2e792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_answers', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'short_answers', ['session_id'])
    op.create_foreign_key(None, 'short_answers', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_answers', type_='foreignkey')
    op.drop_constraint(None, 'short_answers', type_='unique')
    op.drop_column('short_answers', 'session_id')
    # ### end Alembic commands ###
