"""index

Revision ID: fb7c49712467
Revises: a8335ed8ca30
Create Date: 2026-01-10 23:18:16.901529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7c49712467'
down_revision: Union[str, Sequence[str], None] = 'a8335ed8ca30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('short_answer_attempts_session_id_fkey'), 'short_answer_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'short_answer_attempts', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_answer_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('short_answer_attempts_session_id_fkey'), 'short_answer_attempts', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
